# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2021-04-21 00:33+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=cp1252\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: pygettext.py 1.5\n"


#: main.py:117
msgid "Error: Timed out."
msgstr ""

#: main.py:118
msgid "Your request has expired. Execute the command again!"
msgstr ""

#: main.py:119
msgid "Error: Invalid data entered."
msgstr ""

#: main.py:120 main.py:122 main.py:124
msgid "Operation cancelled."
msgstr ""

#: main.py:121
msgid "Error: Invalid reaction entered."
msgstr ""

#: main.py:123
msgid "Error: Invalid format entered."
msgstr ""

#: main.py:125
msgid "Error: Insufficient permissions."
msgstr ""

#: main.py:126
msgid ""
"You did not meet the checks to execute this command. This could also be caused by incorrect configuration. \n"
"Type `{prefix}help` for a list of available commands."
msgstr ""

#: main.py:127
msgid "Error: This command is on cooldown."
msgstr ""

#: main.py:128
msgid "Error: Missing module."
msgstr ""

#: main.py:129
msgid "This operation is missing a module."
msgstr ""

#: main.py:130
msgid "Error: Max concurrency reached!"
msgstr ""

#: main.py:131
msgid "You have reached the maximum amount of instances for this command."
msgstr ""

#: main.py:134
msgid "Warning: Invalid data entered."
msgstr ""

#: main.py:135
msgid "Please check command usage."
msgstr ""

#: main.py:136
msgid "Warning: Invalid reaction entered."
msgstr ""

#: main.py:137
msgid "Please enter a valid reaction."
msgstr ""

#: main.py:138
msgid "Warning: Invalid format entered."
msgstr ""

#: main.py:139
msgid "Please try entering valid data."
msgstr ""

#: main.py:140
msgid "Requested by {user_name}#{discrim}"
msgstr ""

#: main.py:141
msgid "Unknown command!"
msgstr ""

#: main.py:494
msgid ""
"You can also use `{prefix}help <command>` to get more information about a specific command.\n"
"\n"
msgstr ""

#: main.py:494
msgid "__Available commands:__"
msgstr ""

#: main.py:513
msgid "Command: {prefix}{command}"
msgstr ""

#: main.py:515 main.py:517
msgid "Description:"
msgstr ""

#: main.py:519
msgid "Usage:"
msgstr ""

#: main.py:524
msgid "Aliases:"
msgstr ""

#: main.py:532 main.py:542 main.py:587
msgid "Use `{prefix}help` for a list of available commands."
msgstr ""

#: main.py:579 main.py:583
msgid "Did you mean `{prefix}{match}`?"
msgstr ""

#: main.py:593
msgid "Please retry in: `{cooldown}`"
msgstr ""

#: main.py:598
msgid "Missing argument."
msgstr ""

#: main.py:598
msgid ""
"One or more arguments are missing. \n"
"__Hint:__ You can use `{prefix}help {command_name}` to view command usage."
msgstr ""

#: main.py:608
msgid "Cannot find user by that name"
msgstr ""

#: main.py:608
msgid ""
"Please check if you typed everything correctly, then try again.\n"
"**Error:**```{error}```"
msgstr ""

#: main.py:611
msgid "Bad argument"
msgstr ""

#: main.py:611
msgid ""
"Invalid data entered! Check `{prefix}help {command_name}` for more information.\n"
"**Error:**```{error}```"
msgstr ""

#: main.py:615
msgid "Too many arguments"
msgstr ""

#: main.py:615
msgid "You have provided more arguments than what `{prefix}{command_name}` can take. Check `{prefix}help {command_name}` for more information."
msgstr ""

#: main.py:637
msgid "Beep Boop!"
msgstr ""

#: main.py:637
msgid "I have been summoned to this server. Use `{prefix}help` to see what I can do!"
msgstr ""

